import sys
import setuptools
import pathlib

install_requires = ["astropy"]
tests_require = ["pytest", "pytest-cov", "pytest-flake8", "asynctest", "pytest-asyncio"]
scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""
tools_path = pathlib.PurePosixPath(setuptools.__path__[0])
base_prefix = pathlib.PurePosixPath(sys.base_prefix)
data_files_path = tools_path.relative_to(base_prefix).parents[1]

setuptools.setup(
    name="PhidgetMountController",
    description="PhidgetMountController",
    setup_requires=["setuptools_scm", "pytest-runner"],
    install_requires=install_requires,
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    tests_require=tests_require,
    license="GPL",
)
